// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc0yslv3RQaxs_eO_kcNQURsV5SFzcOI4',
    appId: '1:341116210328:web:d4f9a03927e2436c3694ed',
    messagingSenderId: '341116210328',
    projectId: 'ai-appjam-880cc',
    authDomain: 'ai-appjam-880cc.firebaseapp.com',
    storageBucket: 'ai-appjam-880cc.appspot.com',
    measurementId: 'G-KPC4STYL45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqTC-Y2WkYfTuBrTgTSltz8-iWNQDtWcg',
    appId: '1:341116210328:android:622a6bbf8ddfe1483694ed',
    messagingSenderId: '341116210328',
    projectId: 'ai-appjam-880cc',
    storageBucket: 'ai-appjam-880cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjUaduJ8tPOsbPdMUMhuZ2qB30RBBf1Uc',
    appId: '1:341116210328:ios:36b1c2caecf6bf5b3694ed',
    messagingSenderId: '341116210328',
    projectId: 'ai-appjam-880cc',
    storageBucket: 'ai-appjam-880cc.appspot.com',
    iosBundleId: 'com.example.aiAppjam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjUaduJ8tPOsbPdMUMhuZ2qB30RBBf1Uc',
    appId: '1:341116210328:ios:36b1c2caecf6bf5b3694ed',
    messagingSenderId: '341116210328',
    projectId: 'ai-appjam-880cc',
    storageBucket: 'ai-appjam-880cc.appspot.com',
    iosBundleId: 'com.example.aiAppjam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc0yslv3RQaxs_eO_kcNQURsV5SFzcOI4',
    appId: '1:341116210328:web:2d2eab6bbcb65e623694ed',
    messagingSenderId: '341116210328',
    projectId: 'ai-appjam-880cc',
    authDomain: 'ai-appjam-880cc.firebaseapp.com',
    storageBucket: 'ai-appjam-880cc.appspot.com',
    measurementId: 'G-W9DHK29YB4',
  );
}
